@startuml

start
:escobaGame.welcomeMessage();
:User player = escobaGame.createHumanUser();
:User appPlayer = escobaGame.createAppUser();
:Boolean playAgain = true;
repeat
    :new EscobaMatch(player, appPlayer);
    :boolean isPlayerDealer = false;
    repeat
        :EscobaMatch escobaMatch = new EscobaMatch(player, appPlayer);
        :escobaMatch.startRound(isPlayerDealer);
        :escobaMatch.playRound(isPlayerDealer);
        :isPlayerDealer = !isPlayerDealer;
        :escobaMatch.calculateScore(escobaMatchRound);
    repeat while (!escobaMatch.isFinish())
    :playAgain = escobaGame.wantPlayAgain();
repeat while (playAgain)
end

@enduml