// <auto-generated />
using DependencyInyection.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DependencyInyection.Migrations
{
    [DbContext(typeof(CountryDbContext))]
    [Migration("20240530040644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DependencyInyection.Domain.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = "2",
                            Name = "France"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Alemania"
                        },
                        new
                        {
                            Id = "5",
                            Name = "Portugal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
