CREATE DATABASE ESTANCIERO_DB;
GO;
USE ESTANCIERO_DB
GO;
CREATE TABLE ZONES(
id_zone INT IDENTITY(1,1),
zone VARCHAR(20),

CONSTRAINT pk_ZONES PRIMARY KEY(id_zone)
);
GO;
CREATE TABLE PLAYER_STYLES(
id_player_style INT IDENTITY(1,1),
player_style VARCHAR(20) 

CONSTRAINT pk_PLAYER_STYLES PRIMARY KEY (id_player_style)
);
GO;
CREATE TABLE BOARD_SLOT_TYPES(
id_board_slot_type INT IDENTITY(1,1),
slot_type VARCHAR(20)

CONSTRAINT pk_BOARD_SLOT_TYPES PRIMARY KEY (id_board_slot_type)
);
GO;
CREATE TABLE BOT_PLAYER(
id_bot_player INT IDENTITY(1,1),
id_player_style INT ,
player_name VARCHAR(20),
);
GO;
CREATE TABLE PROVINCES(
id_province INT IDENTITY(1,1),
id_zone INT,
province VARCHAR(20),
ranch_price INT,

CONSTRAINT pk_PROVINCES PRIMARY KEY (id_province),
CONSTRAINT fk_PROVINCES_ZONES FOREIGN KEY (id_zone) REFERENCES ZONES(id_zone)
);
GO
CREATE TABLE RENTAL_PRICES(
id_rental_price INT IDENTITY(1,1),
id_board_slot INT,
count INT,
price INT

CONSTRAINT pk_RENTAL_PRICES PRIMARY KEY (id_rental_price),
CONSTRAINT fk_RENTAL_PRICES_BOARD_SLOTS FOREIGN KEY (id_board_slot) REFERENCES BOARD_SLOTS(id_board_slot)
);
GO
CREATE TABLE BOARD_SLOTS(
id_board_slot INT NOT NULL,
id_board_slot_type INT ,
id_province INT,
slot_name VARCHAR(20),
position INT

CONSTRAINT pk_BOARD_SLOTS PRIMARY KEY (id_board_slot),
CONSTRAINT fk_BOARD_SLOTS_BOARD FOREIGN KEY (id_board_slot_type) REFERENCES BOARD_SLOT_TYPES(id_board_slot_type),
CONSTRAINT fk_BOARD_SLOTS_PROVINCES FOREIGN KEY (id_province) REFERENCES PROVINCES(id_province)

);
GO;
CREATE TABLE SPECIAL_CARDS(
id_special_card INT IDENTITY(1,1),
id_board_slot_type INT,
card_message VARCHAR(200),
amount INT,
to_position INT

CONSTRAINT pk_SPECIAL_CARDS PRIMARY KEY(id_special_card)
CONSTRAINT fk_SPECIAL_CARDS_BOARD FOREIGN KEY(id_board_slot_type) REFERENCES BOARD_SLOT_TYPES(id_board_slot_type)
);
GO;

